name: CI
on: push

jobs:
  enable-github-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python script
        run: python .github/workflows/example.py 1
      - name: Gather Repository Collaborators
        id: repository-collaborators-response
        uses: indiesdev/curl@v1.1
        with:
          url: https://api.github.com/repos/Bearmijos/Peer-To-Peer-Renting/collaborators
          method: 'GET'
          accept: 200, 404
          headers: '{ Authorization: Bearer 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 }'
          body: ''
          timeout: 10000
          retries: 5
      - name: Set Respository Collaborators Response
        id: collaborators-response
        run: echo ::set-output name=collaborators-response::'${{ steps.repository-collaborators-response.outputs.response }}'
      - name: Hello
        uses: sergeysova/jq-action@v2
        with:
          cmd: echo '{} {}' | jq -s add > wow-elk.txt
      - name: Call ELK API
        id: elk
        run: echo 'Hello' ${{ steps.repository-collaborators-response.outputs.response }}

